branches:
  only:
  - master

language: node_js
node_js:
  - 12

workspaces:
  use:
    - mac-binaries

script:
  - |
    defaults read loginwindow SystemVersionStampAsString
    node node/test/start.js build

jobs:
  include:
    - stage: Build
      os: osx
      osx_image: xcode11.2
      cache:
        directories:
          - cmake-3.15.5-Darwin-x86_64
      workspaces:
        create:
          name: mac-binaries
          paths:
            - build
      script:
        - |
          if [ ! -d "cmake-3.15.5-Darwin-x86_64" ]; then
            curl -L https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Darwin-x86_64.tar.gz | tar xz
          fi
          export PATH=$PWD/cmake-3.15.5-Darwin-x86_64/CMake.app/Contents/bin:$PATH
          cmake --version
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -S node -B build
          cmake --build build --config Release

    - stage: Test on older versions of macOS
      os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode8.3

    - os: osx
      osx_image: xcode7.3
