branches:
  only:
  - master

language: node_js
node_js:
  - 12

script:
  - |
    brew upgrade cmake || true
    cmake --version
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -S node -B build
    cmake --build build --config Release
    node node/test/start.js build

jobs:
  include:
    - stage: Build and test
      os: osx
      osx_image: xcode11.2
      workspaces:
        create:
          name: mac-binaries
          paths:
            - build

    - stage: Test on older versions of macOS
      os: osx
      osx_image: xcode9.4
      workspaces:
        use:
          - mac-binaries
      script: node node/test/start.js build

    - os: osx
      osx_image: xcode8.3
      workspaces:
        use:
          - mac-binaries
      script: node node/test/start.js build

    - os: osx
      osx_image: xcode7.3
      workspaces:
        use:
          - mac-binaries
      script: node node/test/start.js build


    - os: osx
      osx_image: xcode6.4
      workspaces:
        use:
          - mac-binaries
      script: node node/test/start.js build

    