language: node_js
node_js:
  - 12

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - libgtk-3-dev
    - libwebkit2gtk-4.0-dev 

jobs:
  include:
    - os: linux
      dist: xenial
      env:
        - DG_CMAKE_GENERATOR="Unix Makefiles"
        - DG_DIST_PATH="build/Release"
      services:
        - xvfb

    - os: osx
      osx_image: xcode11.2
      env:
        - DG_CMAKE_GENERATOR="Unix Makefiles"
        - DG_DIST_PATH="build"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
      sudo update-alternatives --config gcc

      wget https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.tar.gz
      tar -xvf cmake-3.15.5-Linux-x86_64.tar.gz > /dev/null
      export PATH=$PWD/cmake-3.15.5-Linux-x86_64/bin:$PATH
    fi
    
install:
  - |
    cmake --version
    mkdir build
    npm ci
    cmake -G "$DG_CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release -S node -B build
    cmake --build build --config Release
    
script: node node/test/start.js $DG_DIST_PATH
