language: node_js
node_js:
  - 12

jobs:
  include:
    - os: linux
      dist: xenial
      env:
        - DG_CMAKE_GENERATOR="Unix Makefiles"
        - DG_DIST_PATH="build/Release"
      services:
        - xvfb

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get -q update
      
      sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev g++-8
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
      sudo update-alternatives --config gcc


      mkdir cmake-install
      wget https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.tar.gz
      tar -xvf cmake-3.15.5-Linux-x86_64.tar.gz > /dev/null
      mv cmake-3.15.5-Linux-x86_64.tar.gz cmake-install
      export PATH=$PWD/cmake-install:$PWD/cmake-install/bin:$PATH
    fi
    
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install cmake
    fi
    
install:
  - |
    npm ci
    cmake -G "$DG_CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release -S node -B build
    cmake --build build --config Release
    
script: node node/test/start.js $DG_DIST_PATH
