trigger:
  - master

pr:
  - master

jobs:
  - job: BuildAndTest
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
          deskGapPlatform: 'linux-x64'
        win:
          imageName: 'windows-2019'
          deskGapPlatform: 'win32-ia32'
        mac:
          imageName: 'macos-10.14'
          deskGapPlatform: 'darwin-x64'
    pool:
      vmImage: $(imageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - script: |
        wget https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.tar.gz
        tar -xvf cmake-3.15.5-Linux-x86_64.tar.gz > /dev/null
        export PATH=$PWD/cmake-3.15.5-Linux-x86_64/bin:$PATH
        echo "##vso[task.setvariable variable=PATH]$PATH"
      condition: eq( variables['Agent.OS'], 'Linux' )
      displayName: 'Install the up-to-date version of CMake on Linux'

    - script: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test > /dev/null
        sudo apt-get update -y  > /dev/null
        sudo apt-get install -y g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
        sudo update-alternatives --config gcc
      condition: eq( variables['Agent.OS'], 'Linux' )
      displayName: 'Install gcc-8 and g++-8 on Linux'

    - script: |
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      condition: eq( variables['Agent.OS'], 'Linux' )
      displayName: 'Install dev files of gtk and webkit on Linux'

    - script: |
        brew install cmake
      condition: eq( variables['Agent.OS'], 'Darwin' )
      displayName: 'Install the up-to-date version of CMake on macOS'

    - script: npm ci
      displayName: 'npm ci'

    - bash: |
        cmake --version
        bash node/scripts/dist.sh
      displayName: 'Build'

    - script: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 6
      displayName: Start xvfb
      condition: eq(variables['Agent.OS'], 'Linux')

    - bash:
        node node/test/start.js node/dist_build/dist
      displayName: 'Test'
      env:
        DISPLAY: ':99.0'

    - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: node/dist_build/dist
          artifactName: $(deskGapPlatform)

  - job: TestOnOlderWindows
    dependsOn: BuildAndTest
    strategy:
      matrix:
        win2016:
          imageName: 'vs2017-win2016'
        win2012r2:
          imageName: 'vs2015-win2012r2'
    pool:
      vmImage: $(imageName)
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadType: 'single'
        artifactName: 'win32-ia32'
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: npm ci
      displayName: 'npm ci'
    - script: node node/test/start.js win32-ia32/dist
      displayName: 'Test'
