trigger:
  - master

pr:
  - master

jobs:
  - job: build
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
          cmakeGenerator: 'Unix Makefiles'
          buildDistPath: 'build/Release'
        mac:
          imageName: 'macos-10.14'
          cmakeGenerator: 'Unix Makefiles'
          buildDistPath: 'build'
    pool:
      vmImage: $(imageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
    - script: |
        sudo apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
      condition: eq( variables['Agent.OS'], 'Linux' )
      displayName: 'Setup the apt repos on Linux'

    - script: |
        sudo rm -rf /usr/local/bin/cmake*
        sudo rm -rf /usr/local/bin/ctest*
        sudo rm -rf /usr/local/doc/cmake
        sudo rm -rf /usr/local/man/man1/cmake*
        sudo rm -rf /usr/local/man/man1/ctest*
        sudo rm -rf /usr/local/man/man7/cmake*
        sudo rm -rf /usr/local/share/cmake*
        sudo apt-get install -y cmake
      condition: eq( variables['Agent.OS'], 'Linux' )
      displayName: 'Install the up-to-date version of CMake on Linux'

    - script: |
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      condition: eq( variables['Agent.OS'], 'Linux' )
      displayName: 'Install dev files of gtk and webkit on Linux'

    - script: |
        sudo apt-get install -y g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
        sudo update-alternatives --config gcc
      condition: eq( variables['Agent.OS'], 'Linux' )
      displayName: 'Install gcc-8 and g++-8 on Linux'

    - script: |
        brew install cmake
      condition: eq( variables['Agent.OS'], 'Darwin' )
      displayName: 'Install the up-to-date version of CMake on macOS'

    - script: |
        npm ci
        cmake -G '$(cmakeGenerator)' -DCMAKE_BUILD_TYPE=Release -S node -B build
        cmake --build build --target all --config Release
      displayName: 'Build'

    - script: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      displayName: Start xvfb
      condition: eq(variables['Agent.OS'], 'Linux')

    - script:
        node node/test/start.js $(buildDistPath)
      displayName: 'test'
      env:
        DISPLAY: ':99.0'
