[build]
  base = "docs/"
  command = "bash build.sh"
  publish = "docs/site"

[[redirects]]
  from = "/dl/macos"
  to = "https://dl.bintray.com/patr0nus/DeskGap/deskgap-v0.1.0-darwin-x64.zip"
  status = 302

[[redirects]]
  from = "/dl/win32"
  to = "https://dl.bintray.com/patr0nus/DeskGap/deskgap-v0.1.0-win32-ia32.zip"
  status = 302

[[redirects]]
  from = "/dl/linux"
  to = "https://dl.bintray.com/patr0nus/DeskGap/deskgap-v0.1.0-linux-x64.zip"
  status = 302

[[redirects]]
  from = "/go/win_f12"
  to = "/devtools/"
  status = 302
